### ISSUE TITLE
Null Reference Exception Upon Dragging a Cell

### ISSUE THREAD

**Issue by TanayParikh** [tossnet/Blazor-Calendar#2]
Starting the app and dragging a cell. results in a null ref exception:

```
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Arg_NullReferenceException
System.NullReferenceException: Arg_NullReferenceException
   at BlazorWebAssembly.Pages.Index.DropTask(DragDropParameter dragDropParameter)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object , BindingFlags , Binder , Object[] , CultureInfo )
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at BlazorCalendar.AnnualView.HandleDayOnDrop(DateTime day)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task , ComponentState )
```

**Comment by tossnet** [comment]
hi! I didn't see this problem. It is fixed
